#spring.datasource.url=jdbc:mysql://localhost:3306/login_db
#spring.datasource.username=root
#spring.datasource.password=mahe@123#

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.security.user.name=admin
#spring.security.user.password=admin
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=50MB
#server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d71a8a6a2pns73f1p03g-a:5432/newdata_4bcu
spring.datasource.username=newdata_4bcu_user
spring.datasource.password=GGZGKJ5JerXUEG3Sse6DElUgMEildd0a
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:5432}

